export const pieceSets = [
  "alpha",
  "anarcandy",
  "caliente",
  "california",
  "cardinal",
  "cburnett",
  "celtic",
  "chess7",
  "chessnut",
  "chicago",
  "companion",
  "cooke",
  "dubrovny",
  "fantasy",
  "firi",
  "fresa",
  "gioco",
  "governor",
  "horsey",
  "icpieces",
  "iowa",
  "iowa",
  "kiwen-suwi",
  "kosal",
  "leipzig",
  "letter",
  "maestro",
  "merida",
  "monarchy",
  "mpchess",
  "oslo",
  "pirouetti",
  "pixel",
  "reillycraig",
  "rhosgfx",
  "riohacha",
  "shapes",
  "spatial",
  "staunty",
  "symmetric",
  "tatiana",
  "xkcd",
];

export const board_themes = [
  { name: "Brown", css_class: "theme-brown", preview: "./backgrounds/brown.svg" },
  { name: "Green", css_class: "theme-green", preview: "./backgrounds/green.svg" },
  { name: "Blue", css_class: "theme-blue", preview: "./backgrounds/blue.svg" },
  { name: "Red", css_class: "theme-red", preview: "./backgrounds/purple.svg" },
];
